***************************************************************************
*                                                                         *
* The Software Experience #2                                              *
* Written and Produced by Tim Meekins                                     *
* Zavtra Software                                                         *
*                                                                         *
* Copyright 1990 by Tim Meekins, distribution rights granted, all other   *
* rights are reserved.                                                    *
*                                                                         *
***************************************************************************
*                                                                         *
* FUGUE.ASM                                                               *
*  - Data for Bach's Toccata & Fugue in D Minor, BWV 565.                 *
*                                                                         *
***************************************************************************

               copy  seq.h

FugueData      DATA

Fugue          anop
;
; measure 1
;
               dc    i1'1,settempo,32,playnote,1,A5,playnote,2,A4,endcmd'
               dc    i1'1,playnote,1,G5,playnote,2,G4,endcmd'
               dc    i1'14,playnote,1,A5,playnote,2,A4,endcmd'
               dc    i1'2,stopnote,1,stopnote,2,endcmd'
               dc    i1'1,playnote,1,G5,playnote,2,G4,endcmd'
               dc    i1'1,playnote,1,F5,playnote,2,F4,endcmd'
               dc    i1'1,playnote,1,E5,playnote,2,E4,endcmd'
               dc    i1'1,playnote,1,D5,playnote,2,D4,endcmd'
               dc    i1'8,playnote,1,C5s,playnote,2,C4s,endcmd'
               dc    i1'8,playnote,1,D5,playnote,2,D4,endcmd'
               dc    i1'8,stopnote,1,stopnote,2,endcmd'

               dc    i1'1,playnote,1,A4,playnote,2,A3,endcmd'
               dc    i1'1,playnote,1,G4,playnote,2,G3,endcmd'
               dc    i1'14,playnote,1,A4,playnote,2,A3,endcmd'
               dc    i1'2,stopnote,1,stopnote,2,endcmd'
               dc    i1'4,playnote,1,E4,playnote,2,E3,endcmd'
               dc    i1'4,playnote,1,F4,playnote,2,F3,endcmd'
               dc    i1'4,playnote,1,C4s,playnote,2,C3s,endcmd'
               dc    i1'8,playnote,1,D4,playnote,2,D3,endcmd'
               dc    i1'8,stopnote,1,stopnote,2,endcmd'
;
; measure 2
;
               dc    i1'1,playnote,1,A3,playnote,2,A2,endcmd'
               dc    i1'1,playnote,1,G3,playnote,2,G3,endcmd'
               dc    i1'14,playnote,1,A3,playnote,2,A2,endcmd'
               dc    i1'2,stopnote,1,stopnote,2,endcmd'
               dc    i1'1,playnote,1,G3,playnote,2,G2,endcmd'
               dc    i1'1,playnote,1,F3,playnote,2,F2,endcmd'
               dc    i1'1,playnote,1,E3,playnote,2,E2,endcmd'
               dc    i1'1,playnote,1,D3,playnote,2,D2,endcmd'
               dc    i1'8,playnote,1,C3s,playnote,2,C2s,endcmd'
               dc    i1'8,playnote,1,D3,playnote,2,D2,endcmd'
               dc    i1'8,stopnote,1,stopnote,2,endcmd'

               dc    i1'8,playnote,1,D2,endcmd'
               dc    i1'8,playnote,2,C3s,endcmd'
               dc    i1'8,playnote,3,E3,endcmd'
               dc    i1'8,playnote,4,G3,endcmd'
               dc    i1'8,playnote,5,A3s,endcmd'
               dc    i1'8,playnote,6,C4s,endcmd'
               dc    i1'16,playnote,7,E4,endcmd'
;
; measure 3
;
               dc    i1'16,stopnote,7,playnote,6,D4,playnote,5,A3'
               dc    i1'playnote,3,D3,stopnote,2,endcmd'
               dc    i1'8,playnote,4,E3,endcmd'
               dc    i1'24,playnote,4,F4s,endcmd'
               dc    i1'16,stopnote,6,stopnote,5,stopnote,4,stopnote,3'
               dc    i1'stopnote,1,endcmd'

               dc    i1'2,settempo,32,playnote,1,C4s,playnote,2,C3s,endcmd'
;
; measure 4
;
               dc    i1'1,playnote,1,D4,playnote,2,D3,endcmd'
               dc    i1'1,playnote,1,E4,playnote,2,E3,endcmd'
               dc    i1'1,playnote,1,C4s,playnote,2,C3s,endcmd'
               dc    i1'1,playnote,1,D4,playnote,2,D3,endcmd'
               dc    i1'1,playnote,1,E4,playnote,2,E3,endcmd'
               dc    i1'1,playnote,1,C4s,playnote,2,C3s,endcmd'
               dc    i1'1,playnote,1,D4,playnote,2,D3,endcmd'
               dc    i1'1,playnote,1,E4,playnote,2,E3,endcmd'
               dc    i1'1,playnote,1,C4s,playnote,2,C3s,endcmd'
               dc    i1'1,playnote,1,D4,playnote,2,D3,endcmd'
               dc    i1'1,playnote,1,E4,playnote,2,E3,endcmd'
               dc    i1'1,playnote,1,F4,playnote,2,F3,endcmd'
               dc    i1'1,playnote,1,G4,playnote,2,G3,endcmd'
               dc    i1'1,playnote,1,E4,playnote,2,E3,endcmd'
               dc    i1'1,playnote,1,F4,playnote,2,F3,endcmd'
               dc    i1'1,playnote,1,G4,playnote,2,G3,endcmd'
               dc    i1'1,playnote,1,E4,playnote,2,E3,endcmd'
               dc    i1'1,playnote,1,F4,playnote,2,F3,endcmd'
               dc    i1'1,playnote,1,G4,playnote,2,G3,endcmd'
               dc    i1'1,playnote,1,E4,playnote,2,E3,endcmd'
               dc    i1'1,playnote,1,F4,playnote,2,F3,endcmd'
               dc    i1'1,playnote,1,G4,playnote,2,G3,endcmd'
;
; measure 5
;
               dc    i1'1,playnote,1,A4,playnote,2,A3,endcmd'
               dc    i1'1,playnote,1,A4s,playnote,2,A3s,endcmd'
               dc    i1'1,playnote,1,G4,playnote,2,G3,endcmd'
               dc    i1'1,playnote,1,A4,playnote,2,A3,endcmd'
               dc    i1'1,playnote,1,A4s,playnote,2,A3s,endcmd'
               dc    i1'1,playnote,1,G4,playnote,2,G3,endcmd'
               dc    i1'1,playnote,1,A4,playnote,2,A3,endcmd'
               dc    i1'1,playnote,1,A4s,playnote,2,A3s,endcmd'
               dc    i1'1,playnote,1,G4,playnote,2,G3,endcmd'
               dc    i1'4,playnote,1,A4,playnote,2,A3,endcmd'
               dc    i1'8,stopnote,1,stopnote,2,endcmd'

               dc    i1'2,playnote,1,C5s,playnote,2,C4s,endcmd'
;
; measure 6
;
               dc    i1'1,playnote,1,D5,playnote,2,D4,endcmd'
               dc    i1'1,playnote,1,E5,playnote,2,E4,endcmd'
               dc    i1'1,playnote,1,C5s,playnote,2,C4s,endcmd'
               dc    i1'1,playnote,1,D5,playnote,2,D4,endcmd'
               dc    i1'1,playnote,1,E5,playnote,2,E4,endcmd'
               dc    i1'1,playnote,1,C5s,playnote,2,C4s,endcmd'
               dc    i1'1,playnote,1,D5,playnote,2,D4,endcmd'
               dc    i1'1,playnote,1,E5,playnote,2,E4,endcmd'
               dc    i1'1,playnote,1,C5s,playnote,2,C4s,endcmd'
               dc    i1'1,playnote,1,D5,playnote,2,D4,endcmd'
               dc    i1'1,playnote,1,E5,playnote,2,E4,endcmd'
               dc    i1'1,playnote,1,F5,playnote,2,F4,endcmd'
               dc    i1'1,playnote,1,G5,playnote,2,G4,endcmd'
               dc    i1'1,playnote,1,E5,playnote,2,E4,endcmd'
               dc    i1'1,playnote,1,F5,playnote,2,F4,endcmd'
               dc    i1'1,playnote,1,G5,playnote,2,G4,endcmd'
               dc    i1'1,playnote,1,E5,playnote,2,E4,endcmd'
               dc    i1'1,playnote,1,F5,playnote,2,F4,endcmd'
               dc    i1'1,playnote,1,G5,playnote,2,G4,endcmd'
               dc    i1'1,playnote,1,E5,playnote,2,E4,endcmd'
               dc    i1'1,playnote,1,F5,playnote,2,F4,endcmd'
               dc    i1'1,playnote,1,G5,playnote,2,G4,endcmd'
;
; measure 7
;
               dc    i1'1,playnote,1,A5,playnote,2,A4,endcmd'
               dc    i1'1,playnote,1,A5s,playnote,2,A4s,endcmd'
               dc    i1'1,playnote,1,G5,playnote,2,G4,endcmd'
               dc    i1'1,playnote,1,A5,playnote,2,A4,endcmd'
               dc    i1'1,playnote,1,A5s,playnote,2,A4s,endcmd'
               dc    i1'1,playnote,1,G5,playnote,2,G4,endcmd'
               dc    i1'1,playnote,1,A5,playnote,2,A4,endcmd'
               dc    i1'1,playnote,1,A5s,playnote,2,A4s,endcmd'
               dc    i1'1,playnote,1,G5,playnote,2,G4,endcmd'
               dc    i1'4,playnote,1,A5,playnote,2,A4,endcmd'
               dc    i1'8,stopnote,1,stopnote,2,endcmd'

               dc    i1'2,playnote,1,A5,playnote,2,A4,endcmd'
;
; measure 8
;
               dc    i1'1,playnote,1,G5,playnote,2,G4,endcmd'
               dc    i1'1,playnote,1,A5s,playnote,2,A4s,endcmd'
               dc    i1'1,playnote,1,E5,playnote,2,E4,endcmd'
               dc    i1'1,playnote,1,G5,playnote,2,G4,endcmd'
               dc    i1'1,playnote,1,A5s,playnote,2,A4s,endcmd'
               dc    i1'1,playnote,1,E5,playnote,2,E4,endcmd'
               dc    i1'1,playnote,1,F5,playnote,2,F4,endcmd'
               dc    i1'1,playnote,1,A5,playnote,2,A4,endcmd'
               dc    i1'1,playnote,1,D5,playnote,2,D4,endcmd'
               dc    i1'1,playnote,1,F5,playnote,2,F4,endcmd'
               dc    i1'1,playnote,1,A5,playnote,2,A4,endcmd'
               dc    i1'1,playnote,1,D5,playnote,2,D4,endcmd'
               dc    i1'1,playnote,1,E5,playnote,2,E4,endcmd'
               dc    i1'1,playnote,1,G5,playnote,2,G4,endcmd'
               dc    i1'1,playnote,1,C5,playnote,2,C4,endcmd'
               dc    i1'1,playnote,1,E5,playnote,2,E4,endcmd'
               dc    i1'1,playnote,1,G5,playnote,2,G4,endcmd'
               dc    i1'1,playnote,1,C5,playnote,2,C4,endcmd'
               dc    i1'1,playnote,1,D5,playnote,2,D4,endcmd'
               dc    i1'1,playnote,1,F5,playnote,2,F4,endcmd'
               dc    i1'1,playnote,1,A4s,playnote,2,A3s,endcmd'
               dc    i1'1,playnote,1,D5,playnote,2,D4,endcmd'
               dc    i1'1,playnote,1,F5,playnote,2,F4,endcmd'
               dc    i1'1,playnote,1,A4s,playnote,2,A3s,endcmd'
;
; measure 9
;
               dc    i1'1,playnote,1,C5,playnote,2,C4,endcmd'
               dc    i1'1,playnote,1,E5,playnote,2,E4,endcmd'
               dc    i1'1,playnote,1,A4,playnote,2,A3,endcmd'
               dc    i1'1,playnote,1,C5,playnote,2,C4,endcmd'
               dc    i1'1,playnote,1,E5,playnote,2,E4,endcmd'
               dc    i1'1,playnote,1,A4,playnote,2,A3,endcmd'
               dc    i1'1,playnote,1,A4s,playnote,2,A3s,endcmd'
               dc    i1'1,playnote,1,D5,playnote,2,D4,endcmd'
               dc    i1'1,playnote,1,G4,playnote,2,G3,endcmd'
               dc    i1'1,playnote,1,A4s,playnote,2,A3s,endcmd'
               dc    i1'1,playnote,1,D5,playnote,2,D4,endcmd'
               dc    i1'1,playnote,1,G4,playnote,2,G3,endcmd'
               dc    i1'1,playnote,1,A4,playnote,2,A3,endcmd'
               dc    i1'1,playnote,1,C5,playnote,2,C4,endcmd'
               dc    i1'1,playnote,1,F4,playnote,2,F3,endcmd'
               dc    i1'1,playnote,1,A4,playnote,2,A3,endcmd'
               dc    i1'1,playnote,1,C5,playnote,2,C4,endcmd'
               dc    i1'1,playnote,1,F4,playnote,2,F3,endcmd'
               dc    i1'1,playnote,1,G4,playnote,2,G3,endcmd'
               dc    i1'1,playnote,1,A4s,playnote,2,A3s,endcmd'
               dc    i1'1,playnote,1,E4,playnote,2,E3,endcmd'
               dc    i1'1,playnote,1,G4,playnote,2,G3,endcmd'
               dc    i1'1,playnote,1,A4s,playnote,2,A3s,endcmd'
               dc    i1'1,playnote,1,E4,playnote,2,E3,endcmd'
;
; measure 10
;
               dc    i1'1,playnote,1,F4,playnote,2,F3,endcmd'
               dc    i1'1,playnote,1,A4,playnote,2,A3,endcmd'
               dc    i1'1,playnote,1,D4,playnote,2,D3,endcmd'
               dc    i1'1,playnote,1,F4,playnote,2,F3,endcmd'
               dc    i1'1,playnote,1,A4,playnote,2,A3,endcmd'
               dc    i1'1,playnote,1,D4,playnote,2,D3,endcmd'
               dc    i1'1,playnote,1,E4,playnote,2,E3,endcmd'
               dc    i1'1,playnote,1,G4,playnote,2,G3,endcmd'
               dc    i1'1,playnote,1,C4s,playnote,2,C3s,endcmd'
               dc    i1'1,playnote,1,E4,playnote,2,E3,endcmd'
               dc    i1'1,playnote,1,G4,playnote,2,G3,endcmd'
               dc    i1'1,playnote,1,C4s,playnote,2,C3s,endcmd'
               dc    i1'8,stopnote,1,stopnote,2,playnote,9,D2'
               dc    i1'playnote,10,D2,playnote,11,D2,playnote,12,D2,endcmd'
               dc    i1'16,playnote,1,A4s,playnote,2,G4,playnote,3,E4'
               dc    i1'playnote,4,C4s,playnote,5,A3s,playnote,6,G3'
               dc    i1'playnote,7,E3,playnote,8,C3s,endcmd'
;
; measure 11
;
               dc    i1'1,settempo,24,stopnote,2,stopnote,3,stopnote,4'
               dc    i1'stopnote,5,stopnote,6,stopnote,7,stopnote,8'
               dc    i1'stopnote,9,stopnote,10,stopnote,11,stopnote,12,endcmd'
               dc    i1'1,playnote,1,A4,endcmd'
               dc    i1'1,playnote,1,G4,endcmd'
               dc    i1'1,playnote,1,F4,endcmd'
               dc    i1'1,playnote,1,E4,endcmd'
               dc    i1'1,playnote,1,D4,endcmd'
               dc    i1'1,playnote,1,C4s,endcmd'
               dc    i1'1,playnote,1,B3,endcmd'
               dc    i1'1,playnote,1,C4s,endcmd'
               dc    i1'1,playnote,1,A3,endcmd'
               dc    i1'1,playnote,1,C4s,endcmd'
               dc    i1'1,playnote,1,E4,endcmd'
               dc    i1'1,playnote,1,G4,endcmd'
               dc    i1'1,settempo,16,playnote,1,F4,endcmd'
               dc    i1'1,playnote,1,G4,endcmd'
               dc    i1'1,playnote,1,F4,endcmd'
               dc    i1'1,playnote,1,G4,endcmd'
               dc    i1'1,playnote,1,F4,endcmd'
               dc    i1'1,playnote,1,G4,endcmd'
               dc    i1'1,playnote,1,F4,endcmd'
               dc    i1'1,playnote,1,G4,endcmd'
               dc    i1'1,playnote,1,F4,endcmd'
               dc    i1'1,playnote,1,G4,endcmd'
               dc    i1'1,playnote,1,F4,endcmd'
               dc    i1'1,playnote,1,G4,endcmd'
               dc    i1'1,playnote,1,F4,endcmd'
               dc    i1'1,playnote,1,G4,endcmd'
               dc    i1'2,settempo,32,playnote,1,E4,endcmd'
;
; measure 12
;
               dc    i1'16,playnote,1,F4,playnote,2,D4,playnote,3,A3'
               dc    i1'playnote,4,F3,playnote,5,D3,playnote,6,D2,endcmd'
               dc    i1'10,stopnote,1,stopnote,2,stopnote,3,stopnote,4'
               dc    i1'stopnote,5,stopnote,6,endcmd'
               dc    i1'1,playnote,1,A4,endcmd'
               dc    i1'1,settempo,20,playnote,1,D5,endcmd'
               dc    i1'1,playnote,3,A4,stopnote,1,endcmd'
               dc    i1'1,playnote,1,E5,stopnote,3,endcmd'
               dc    i1'1,playnote,3,A4,stopnote,1,endcmd'
               dc    i1'1,playnote,1,F5,stopnote,3,endcmd'
               dc    i1'1,playnote,3,A4,stopnote,1,endcmd'
               dc    i1'1,playnote,1,D5,stopnote,3,endcmd'
               dc    i1'1,playnote,3,A4,stopnote,1,endcmd'
               dc    i1'1,playnote,1,E5,stopnote,3,endcmd'
               dc    i1'1,playnote,3,A4,stopnote,1,endcmd'
               dc    i1'1,playnote,1,F5,stopnote,3,endcmd'
               dc    i1'1,playnote,3,A4,stopnote,1,endcmd'
               dc    i1'1,playnote,1,G5,stopnote,3,endcmd'
               dc    i1'1,playnote,3,A4,stopnote,1,endcmd'
               dc    i1'1,playnote,1,E5,stopnote,3,endcmd'
               dc    i1'1,playnote,3,A4,stopnote,1,endcmd'
;
; measure 13
;
               dc    i1'1,playnote,1,F5,stopnote,3,endcmd'
               dc    i1'1,playnote,3,A4,stopnote,1,endcmd'
               dc    i1'1,playnote,1,G5,stopnote,3,endcmd'
               dc    i1'1,playnote,3,A4,stopnote,1,endcmd'
               dc    i1'1,playnote,1,A5,stopnote,3,endcmd'
               dc    i1'1,playnote,3,A4,stopnote,1,endcmd'
               dc    i1'1,playnote,1,F5,stopnote,3,endcmd'
               dc    i1'1,playnote,3,A4,stopnote,1,endcmd'
               dc    i1'1,playnote,1,G5,stopnote,3,endcmd'
               dc    i1'1,playnote,3,A4,stopnote,1,endcmd'
               dc    i1'1,playnote,1,A5,stopnote,3,endcmd'
               dc    i1'1,playnote,3,A4,stopnote,1,endcmd'
               dc    i1'1,playnote,1,A5s,stopnote,3,endcmd'
               dc    i1'1,playnote,3,A4,stopnote,1,endcmd'
               dc    i1'1,playnote,1,G5,stopnote,3,endcmd'
               dc    i1'1,playnote,3,A4,stopnote,1,endcmd'
               dc    i1'1,playnote,1,A5,stopnote,3,endcmd'
               dc    i1'1,playnote,3,A4,stopnote,1,endcmd'
               dc    i1'1,playnote,1,F5,stopnote,3,endcmd'
               dc    i1'1,playnote,3,A4,stopnote,1,endcmd'
               dc    i1'1,playnote,1,G5,stopnote,3,endcmd'
               dc    i1'1,playnote,3,A4,stopnote,1,endcmd'
               dc    i1'1,playnote,1,E5,stopnote,3,endcmd'
               dc    i1'1,playnote,3,A4,stopnote,1,endcmd'
               dc    i1'1,playnote,1,F5,stopnote,3,endcmd'
               dc    i1'1,playnote,3,A4,stopnote,1,endcmd'
               dc    i1'1,playnote,1,D5,stopnote,3,endcmd'
               dc    i1'1,playnote,3,A4,stopnote,1,endcmd'
               dc    i1'1,playnote,1,E5,stopnote,3,endcmd'
               dc    i1'1,playnote,3,A4,stopnote,1,endcmd'
               dc    i1'1,playnote,1,C5s,stopnote,3,endcmd'
               dc    i1'1,playnote,3,A4,stopnote,1,endcmd'
;
; measure 14
;
               dc    i1'1,playnote,1,D5,stopnote,3,endcmd'
               dc    i1'1,playnote,3,A4,stopnote,1,endcmd'
               dc    i1'1,playnote,1,A4,stopnote,3,endcmd'
               dc    i1'1,playnote,3,A4,stopnote,1,endcmd'
               dc    i1'1,playnote,1,A4s,stopnote,3,endcmd'
               dc    i1'1,playnote,3,A4,stopnote,1,endcmd'
               dc    i1'1,playnote,1,G4,stopnote,3,endcmd'
               dc    i1'1,playnote,3,A4,stopnote,1,endcmd'
               dc    i1'1,playnote,1,A4,stopnote,3,endcmd'
               dc    i1'1,playnote,3,A4,stopnote,1,endcmd'
               dc    i1'1,playnote,1,F4,stopnote,3,endcmd'
               dc    i1'1,playnote,3,A4,stopnote,1,endcmd'
               dc    i1'1,playnote,1,G4,stopnote,3,endcmd'
               dc    i1'1,playnote,3,A4,stopnote,1,endcmd'
               dc    i1'1,playnote,1,E4,stopnote,3,endcmd'
               dc    i1'1,playnote,3,A4,stopnote,1,endcmd'
               dc    i1'1,playnote,1,F4,stopnote,3,endcmd'
               dc    i1'1,playnote,3,A4,stopnote,1,endcmd'
               dc    i1'1,playnote,1,D4,stopnote,3,endcmd'
               dc    i1'1,playnote,3,A4,stopnote,1,endcmd'
               dc    i1'1,playnote,1,G4,stopnote,3,endcmd'
               dc    i1'1,playnote,3,A4,stopnote,1,endcmd'
               dc    i1'1,playnote,1,E4,stopnote,3,endcmd'
               dc    i1'1,playnote,3,A4,stopnote,1,endcmd'
               dc    i1'1,playnote,1,F4,stopnote,3,endcmd'
               dc    i1'1,playnote,3,A4,stopnote,1,endcmd'
               dc    i1'1,playnote,1,D4,stopnote,3,endcmd'
               dc    i1'1,playnote,3,A4,stopnote,1,endcmd'
               dc    i1'1,playnote,1,E4,stopnote,3,endcmd'
               dc    i1'1,playnote,3,A4,stopnote,1,endcmd'
               dc    i1'1,playnote,1,C4s,stopnote,3,endcmd'
               dc    i1'1,playnote,3,A4,stopnote,1,endcmd'
;
; measure 15
;
               dc    i1'1,playnote,1,D4,stopnote,3,endcmd'
               dc    i1'1,playnote,3,A4,stopnote,1,endcmd'
               dc    i1'1,playnote,1,A3,stopnote,3,endcmd'
               dc    i1'1,playnote,3,A4,stopnote,1,endcmd'
               dc    i1'1,playnote,1,A3s,stopnote,3,endcmd'
               dc    i1'1,playnote,3,A4,stopnote,1,endcmd'
               dc    i1'1,playnote,1,G3,stopnote,3,endcmd'
               dc    i1'1,playnote,3,A4,stopnote,1,endcmd'
               dc    i1'1,playnote,1,A3,stopnote,3,endcmd'
               dc    i1'1,playnote,3,A4,stopnote,1,endcmd'
               dc    i1'1,playnote,1,F3,stopnote,3,endcmd'
               dc    i1'1,playnote,3,A4,stopnote,1,endcmd'
               dc    i1'1,playnote,1,G3,stopnote,3,endcmd'
               dc    i1'1,playnote,3,A4,stopnote,1,endcmd'
               dc    i1'1,playnote,1,E3,stopnote,3,endcmd'
               dc    i1'1,playnote,3,A4,stopnote,1,endcmd'
               dc    i1'1,playnote,1,F3,stopnote,3,endcmd'
               dc    i1'1,playnote,3,A4,stopnote,1,endcmd'
               dc    i1'1,playnote,1,D3,stopnote,3,endcmd'
               dc    i1'1,playnote,3,A4,stopnote,1,endcmd'
               dc    i1'1,playnote,1,G3,stopnote,3,endcmd'
               dc    i1'1,playnote,3,A4,stopnote,1,endcmd'
               dc    i1'1,playnote,1,E3,stopnote,3,endcmd'
               dc    i1'1,playnote,3,A4,stopnote,1,endcmd'
               dc    i1'1,playnote,1,F3,stopnote,3,endcmd'
               dc    i1'1,playnote,3,A4,stopnote,1,endcmd'
               dc    i1'1,playnote,1,D3,stopnote,3,endcmd'
               dc    i1'1,playnote,3,A4,stopnote,1,endcmd'
               dc    i1'1,playnote,1,E3,stopnote,3,endcmd'
               dc    i1'1,playnote,3,A4,stopnote,1,endcmd'
               dc    i1'1,playnote,1,C3s,stopnote,3,endcmd'
               dc    i1'1,playnote,3,A4,stopnote,1,endcmd'
;
; measure 16
;
               dc    i1'4,playnote,2,D3,stopnote,1,stopnote,3,endcmd'
               dc    i1'1,playnote,2,D4,endcmd'
               dc    i1'1,playnote,2,F4,endcmd'
               dc    i1'1,playnote,2,A4s,endcmd'
               dc    i1'1,playnote,2,F4,endcmd'
               dc    i1'1,playnote,2,C4,endcmd'
               dc    i1'1,playnote,2,E4,endcmd'
               dc    i1'1,playnote,2,A4,endcmd'
               dc    i1'1,playnote,2,E4,endcmd'
               dc    i1'1,playnote,2,A3s,endcmd'
               dc    i1'1,playnote,2,D4,endcmd'
               dc    i1'1,playnote,2,G4,endcmd'
               dc    i1'1,playnote,2,D4,endcmd'
               dc    i1'1,playnote,2,A3,endcmd'
               dc    i1'1,playnote,2,C4s,endcmd'
               dc    i1'1,playnote,2,E4,endcmd'
               dc    i1'1,playnote,2,A4,endcmd'
               dc    i1'4,playnote,1,D4,playnote,4,D3,stopnote,2,endcmd'
               dc    i1'4,playnote,1,A4s,playnote,2,F4,endcmd'
               dc    i1'4,playnote,1,A3,playnote,4,C3,stopnote,2,endcmd'
               dc    i1'4,playnote,1,A4,playnote,2,E4,endcmd'
               dc    i1'4,playnote,1,A3s,playnote,4,A2s,stopnote,2,endcmd'
               dc    i1'4,playnote,1,G4,playnote,2,D4,endcmd'
;
; measure 17
;
               dc    i1'8,playnote,1,C4s,playnote,2,A4,playnote,3,E4'
               dc    i1'playnote,4,A2,playnote,5,E4,endcmd'
               dc    i1'1,playnote,2,D4,stopnote,1,stopnote,3,stopnote,4'
               dc    i1'stopnote,5,endcmd'
               dc    i1'1,playnote,2,F4,endcmd'
               dc    i1'1,playnote,2,A4s,endcmd'
               dc    i1'1,playnote,2,F4,endcmd'
               dc    i1'1,playnote,2,C4,endcmd'
               dc    i1'1,playnote,2,E4,endcmd'
               dc    i1'1,playnote,2,A4,endcmd'
               dc    i1'1,playnote,2,E4,endcmd'
               dc    i1'1,playnote,2,A3s,endcmd'
               dc    i1'1,playnote,2,D4,endcmd'
               dc    i1'1,playnote,2,G4,endcmd'
               dc    i1'1,playnote,2,D4,endcmd'
               dc    i1'1,playnote,2,A3,endcmd'
               dc    i1'1,playnote,2,C4s,endcmd'
               dc    i1'1,playnote,2,E4,endcmd'
               dc    i1'1,playnote,2,A4,endcmd'
               dc    i1'4,playnote,1,D4,playnote,4,D3,stopnote,2,endcmd'
               dc    i1'4,playnote,1,A4s,playnote,2,F4,endcmd'
               dc    i1'4,playnote,1,A3,playnote,4,C3,stopnote,2,endcmd'
               dc    i1'4,playnote,1,A4,playnote,2,E4,endcmd'
               dc    i1'4,playnote,1,A3s,playnote,4,A2s,stopnote,2,endcmd'
               dc    i1'4,playnote,1,G4,playnote,2,D4,endcmd'
;
; measure 17
;
               dc    i1'16,playnote,1,A4,playnote,2,E4,playnote,3,C4s'
               dc    i1'playnote,4,E3,playnote,5,A2,endcmd'
               dc    i1'1,stopnote,2,stopnote,3,stopnote,4,stopnote,5,endcmd'
               dc    i1'1,playnote,1,G4,endcmd'
               dc    i1'1,playnote,1,F4,endcmd'
               dc    i1'1,playnote,1,E4,endcmd'
               dc    i1'1,playnote,1,D4,endcmd'
               dc    i1'1,playnote,1,C4s,endcmd'
               dc    i1'1,playnote,1,B3,endcmd'
               dc    i1'1,playnote,1,C4s,endcmd'
               dc    i1'1,playnote,1,A3,endcmd'
               dc    i1'1,playnote,1,B3,endcmd'
               dc    i1'1,playnote,1,C4s,endcmd'
               dc    i1'1,playnote,1,D4,endcmd'
               dc    i1'1,playnote,1,E4,endcmd'
               dc    i1'1,playnote,1,F4,endcmd'
               dc    i1'1,playnote,1,G4,endcmd'
               dc    i1'1,playnote,1,A4,endcmd'
               dc    i1'1,playnote,1,G4,endcmd'
               dc    i1'1,playnote,1,F4,endcmd'
               dc    i1'1,playnote,1,E4,endcmd'
               dc    i1'1,playnote,1,F4,endcmd'
               dc    i1'1,playnote,1,D4,endcmd'
               dc    i1'1,playnote,1,F4,endcmd'
               dc    i1'1,playnote,1,A4,endcmd'
               dc    i1'1,playnote,1,C5s,endcmd'
;
; measure 19
;
               dc    i1'1,playnote,1,D5,endcmd'
               dc    i1'1,playnote,1,A4,endcmd'
               dc    i1'1,playnote,1,B4,endcmd'
               dc    i1'1,playnote,1,C5s,endcmd'
               dc    i1'1,playnote,1,D5,endcmd'
               dc    i1'1,playnote,1,E5,endcmd'
               dc    i1'1,settempo,10,playnote,1,F5,endcmd'
               dc    i1'1,playnote,1,G5,endcmd'
               dc    i1'1,settempo,20,playnote,1,A5,endcmd'
               dc    i1'8,playnote,1,A5s,endcmd'
               dc    i1'4,playnote,1,D5,playnote,4,D3,stopnote,2,endcmd'
               dc    i1'4,playnote,1,A5s,playnote,2,F5,endcmd'
               dc    i1'4,playnote,1,A4,playnote,4,C3,stopnote,2,endcmd'
               dc    i1'4,playnote,1,A5,playnote,2,E5,endcmd'
               dc    i1'4,playnote,1,A4s,playnote,4,A2s,stopnote,2,endcmd'
               dc    i1'4,playnote,1,G5,playnote,2,D5,endcmd'
               dc    i1'8,playnote,1,C5s,playnote,2,A5,playnote,3,E5'
               dc    i1'playnote,4,A2,playnote,5,E4,endcmd'
               dc    i1'1,playnote,2,D5,stopnote,1,stopnote,3,stopnote,4'
               dc    i1'stopnote,5,endcmd'
               dc    i1'1,playnote,2,F5,endcmd'
               dc    i1'1,playnote,2,A5s,endcmd'
               dc    i1'1,playnote,2,F5,endcmd'
;
; measure 20
;
               dc    i1'1,playnote,2,C5,endcmd'
               dc    i1'1,playnote,2,E5,endcmd'
               dc    i1'1,playnote,2,A5,endcmd'
               dc    i1'1,playnote,2,E5,endcmd'
               dc    i1'1,playnote,2,A4s,endcmd'
               dc    i1'1,playnote,2,D5,endcmd'
               dc    i1'1,playnote,2,G5,endcmd'
               dc    i1'1,playnote,2,D5,endcmd'
               dc    i1'1,playnote,2,A4,endcmd'
               dc    i1'1,playnote,2,C5s,endcmd'
               dc    i1'1,playnote,2,E5,endcmd'
               dc    i1'1,playnote,2,A5,endcmd'
               dc    i1'4,playnote,1,D5,playnote,4,D3,stopnote,2,endcmd'
               dc    i1'4,playnote,1,A5s,playnote,2,F5,endcmd'
               dc    i1'4,playnote,1,A4,playnote,4,C3,stopnote,2,endcmd'
               dc    i1'4,playnote,1,A5,playnote,2,E5,endcmd'
               dc    i1'4,playnote,1,A4s,playnote,4,A2s,stopnote,2,endcmd'
               dc    i1'4,playnote,1,G5,playnote,2,D5,endcmd'
               dc    i1'8,playnote,1,C5s,playnote,2,A5,playnote,3,E5'
               dc    i1'playnote,4,A2,playnote,5,E4,endcmd'
               dc    i1'8,playnote,1,B4,playnote,2,F4,playnote,3,D4'
               dc    i1'playnote,4,B3,playnote,5,G2s,endcmd'
;
; measure 21
;
               dc    i1'12,playnote,1,C5s,playnote,2,A4,playnote,3,E4'
               dc    i1'playnote,4,A3,playnote,5,G2,endcmd'
               dc    i1'2,playnote,1,B4,endcmd'
               dc    i1'2,playnote,1,A4,stopnote,2,stopnote,3,stopnote,4'
               dc    i1'stopnote,5,endcmd'
               dc    i1'2,playnote,1,C5s,endcmd'
               dc    i1'1,playnote,1,E5,endcmd'
               dc    i1'1,playnote,1,G5,endcmd'
               dc    i1'2,playnote,1,A5s,endcmd'
               dc    i1'1,playnote,1,A5,endcmd'
               dc    i1'1,playnote,1,G5,endcmd'
               dc    i1'1,playnote,1,F5,endcmd'
               dc    i1'1,playnote,1,E5,endcmd'
               dc    i1'1,playnote,1,F5,endcmd'
               dc    i1'1,playnote,1,E5,endcmd'
               dc    i1'1,playnote,1,D5,endcmd'
               dc    i1'1,playnote,1,C5s,endcmd'
               dc    i1'1,playnote,1,D5,endcmd'
               dc    i1'1,playnote,1,C5,endcmd'
               dc    i1'1,playnote,1,A4s,endcmd'
               dc    i1'1,playnote,1,A4,endcmd'
               dc    i1'1,playnote,1,G4,endcmd'
               dc    i1'1,playnote,1,F4,endcmd'
               dc    i1'1,playnote,1,E4,endcmd'
               dc    i1'1,playnote,1,D4,endcmd'
;
; measure 22
;
               dc    i1'32,playnote,1,E5,playnote,2,C5s,playnote,3,A4s'
               dc    i1'playnote,4,G4,playnote,5,E4,playnote,6,C4s'
               dc    i1'playnote,7,G3,endcmd'
               dc    i1'2,stopnote,1,stopnote,3,stopnote,4,stopnote,6'
               dc    i1'stopnote,7,endcmd'
               dc    i1'2,playnote,2,E5,playnote,5,G4,endcmd'
               dc    i1'2,playnote,2,C5s,playnote,5,E4,endcmd'
               dc    i1'2,playnote,2,A4s,playnote,5,C4s,endcmd'
               dc    i1'2,playnote,2,C5s,playnote,5,E4,endcmd'
               dc    i1'2,playnote,2,A4s,playnote,5,C4s,endcmd'
               dc    i1'2,playnote,2,C5s,playnote,5,E4,endcmd'
               dc    i1'2,playnote,2,E5,playnote,5,G4,endcmd'
               dc    i1'2,playnote,2,C5s,playnote,5,E4,endcmd'
               dc    i1'2,playnote,2,A4s,playnote,5,C4s,endcmd'
               dc    i1'2,playnote,2,C5s,playnote,5,E4,endcmd'
               dc    i1'2,playnote,2,A4s,playnote,5,C4s,endcmd'
;
; measure 23
;
               dc    i1'2,playnote,2,C5s,playnote,5,E4,endcmd'
               dc    i1'2,playnote,2,E5,playnote,5,G4,endcmd'
               dc    i1'2,playnote,2,C5s,playnote,5,E4,endcmd'
               dc    i1'2,playnote,2,A4s,playnote,5,C4s,endcmd'
               dc    i1'2,playnote,2,C5s,playnote,5,E4,endcmd'
               dc    i1'2,playnote,2,A4s,playnote,5,C4s,endcmd'
               dc    i1'2,playnote,2,C5s,playnote,5,E4,endcmd'
               dc    i1'2,playnote,2,E5,playnote,5,G4,endcmd'
               dc    i1'2,playnote,2,C5s,playnote,5,E4,endcmd'
               dc    i1'2,playnote,2,A4s,playnote,5,C4s,endcmd'
               dc    i1'2,playnote,2,C5s,playnote,5,E4,endcmd'
               dc    i1'2,playnote,2,A4s,playnote,5,C4s,endcmd'
               dc    i1'2,playnote,2,G4,playnote,5,A3s,endcmd'
               dc    i1'2,playnote,2,A4s,playnote,5,C4s,endcmd'
               dc    i1'2,playnote,2,G4,playnote,5,A3s,endcmd'
               dc    i1'2,playnote,2,E4,playnote,5,G3,endcmd'
               dc    i1'2,playnote,2,G4,playnote,5,A3s,endcmd'
               dc    i1'2,playnote,2,E4,playnote,5,G3,endcmd'
               dc    i1'2,playnote,2,G4,playnote,5,A3s,endcmd'
               dc    i1'2,playnote,2,A4s,playnote,5,C4s,endcmd'
               dc    i1'2,playnote,2,G4,playnote,5,A3s,endcmd'
               dc    i1'2,playnote,2,E4,playnote,5,G3,endcmd'
               dc    i1'2,playnote,2,G4,playnote,5,A3s,endcmd'
               dc    i1'2,playnote,2,E4,playnote,5,G3,endcmd'
;
; measure 24
;
               dc    i1'2,playnote,2,G4,playnote,5,A3s,endcmd'
               dc    i1'2,playnote,2,A4s,playnote,5,C4s,endcmd'
               dc    i1'2,playnote,2,G4,playnote,5,A3s,endcmd'
               dc    i1'2,playnote,2,E4,playnote,5,G3,endcmd'
               dc    i1'2,playnote,2,G4,playnote,5,A3s,endcmd'
               dc    i1'2,playnote,2,E4,playnote,5,G3,endcmd'
               dc    i1'2,playnote,2,G4,playnote,5,A3s,endcmd'
               dc    i1'2,playnote,2,A4s,playnote,5,C4s,endcmd'
               dc    i1'2,playnote,2,G4,playnote,5,A3s,endcmd'
               dc    i1'2,playnote,2,E4,playnote,5,G3,endcmd'
               dc    i1'2,playnote,2,G4,playnote,5,A3s,endcmd'
               dc    i1'2,playnote,2,E4,playnote,5,G3,endcmd'
               dc    i1'2,playnote,2,C4s,playnote,5,E3,endcmd'
               dc    i1'2,playnote,2,E4,playnote,5,G3,endcmd'
               dc    i1'2,playnote,2,C4s,playnote,5,E3,endcmd'
               dc    i1'2,playnote,2,A3s,playnote,5,C3s,endcmd'
               dc    i1'2,playnote,2,C4s,playnote,5,E3,endcmd'
               dc    i1'2,playnote,2,A3s,playnote,5,C3s,endcmd'
               dc    i1'2,playnote,2,C4s,playnote,5,E3,endcmd'
               dc    i1'2,playnote,2,E4,playnote,5,G3,endcmd'
               dc    i1'2,playnote,2,C4s,playnote,5,E3,endcmd'
               dc    i1'2,playnote,2,A3s,playnote,5,C3s,endcmd'
               dc    i1'2,playnote,2,C4s,playnote,5,E3,endcmd'
               dc    i1'2,playnote,2,A3s,playnote,5,C3s,endcmd'
;
; measure 25
;
               dc    i1'2,playnote,2,C4s,playnote,5,E3,endcmd'
               dc    i1'2,playnote,2,E4,playnote,5,G3,endcmd'
               dc    i1'2,playnote,2,C4s,playnote,5,E3,endcmd'
               dc    i1'2,playnote,2,A3s,playnote,5,C3s,endcmd'
               dc    i1'2,playnote,2,C4s,playnote,5,E3,endcmd'
               dc    i1'2,playnote,2,A3s,playnote,5,C3s,endcmd'
               dc    i1'2,playnote,2,C4s,playnote,5,E3,endcmd'
               dc    i1'2,playnote,2,E4,playnote,5,G3,endcmd'
               dc    i1'2,playnote,2,C4s,playnote,5,E3,endcmd'
               dc    i1'2,playnote,2,A3s,playnote,5,C3s,endcmd'
               dc    i1'2,playnote,2,C4s,playnote,5,E3,endcmd'
               dc    i1'2,playnote,2,A3s,playnote,5,C3s,endcmd'
               dc    i1'2,playnote,2,C4s,playnote,5,E3,endcmd'
               dc    i1'2,playnote,2,E4,playnote,5,G3,endcmd'
               dc    i1'2,playnote,2,C4s,playnote,5,E3,endcmd'
               dc    i1'2,playnote,2,E4,playnote,5,G3,endcmd'
               dc    i1'2,playnote,2,G4,playnote,5,A3s,endcmd'
               dc    i1'2,playnote,2,E4,playnote,5,G3,endcmd'
               dc    i1'2,playnote,2,C4s,playnote,5,E3,endcmd'
               dc    i1'2,playnote,2,E4,playnote,5,G3,endcmd'
               dc    i1'2,playnote,2,C4s,playnote,5,E3,endcmd'
               dc    i1'2,playnote,2,E4,playnote,5,G3,endcmd'
               dc    i1'2,playnote,2,G4,playnote,5,A3s,endcmd'
               dc    i1'2,playnote,2,E4,playnote,5,G3,endcmd'
;
; measure 26
;
               dc    i1'2,playnote,2,C4s,playnote,5,E3,endcmd'
               dc    i1'2,playnote,2,E4,playnote,5,G3,endcmd'
               dc    i1'2,playnote,2,C4s,playnote,5,E3,endcmd'
               dc    i1'2,playnote,2,E4,playnote,5,G3,endcmd'
               dc    i1'2,playnote,2,G4,playnote,5,A3s,endcmd'
               dc    i1'2,playnote,2,E4,playnote,5,G3,endcmd'
               dc    i1'2,playnote,2,C4s,playnote,5,E3,endcmd'
               dc    i1'2,playnote,2,E4,playnote,5,G3,endcmd'
               dc    i1'2,playnote,2,C4s,playnote,5,E3,endcmd'
               dc    i1'2,playnote,2,E4,playnote,5,G3,endcmd'
               dc    i1'2,playnote,2,G4,playnote,5,A3s,endcmd'
               dc    i1'2,playnote,2,E4,playnote,5,G3,endcmd'
               dc    i1'2,playnote,2,G4,playnote,5,E3,endcmd'
               dc    i1'2,playnote,2,A4s,playnote,5,G3,endcmd'
               dc    i1'2,playnote,2,G4,playnote,5,E3,endcmd'
               dc    i1'2,playnote,2,A4s,playnote,5,G3,endcmd'
               dc    i1'2,playnote,2,G4,playnote,5,E3,endcmd'
               dc    i1'2,playnote,2,A4s,playnote,5,G3,endcmd'
               dc    i1'2,playnote,2,G4,playnote,5,A3s,endcmd'
               dc    i1'2,playnote,2,A4s,playnote,5,C4s,endcmd'
               dc    i1'2,playnote,2,G4,playnote,5,A3s,endcmd'
               dc    i1'2,playnote,2,A4s,playnote,5,C4s,endcmd'
               dc    i1'2,playnote,2,G4,playnote,5,A3s,endcmd'
               dc    i1'2,playnote,2,A4s,playnote,5,C4s,endcmd'
;
; measure 27
;
               dc    i1'2,playnote,2,C5s,playnote,5,E4,endcmd'
               dc    i1'2,playnote,2,A4s,playnote,5,C4s,endcmd'
               dc    i1'2,playnote,2,C5s,playnote,5,E4,endcmd'
               dc    i1'2,playnote,2,E5,playnote,5,C4s,endcmd'
               dc    i1'2,playnote,2,C5s,playnote,5,E4,endcmd'
               dc    i1'2,playnote,2,E5,playnote,5,C4s,endcmd'
               dc    i1'2,playnote,2,C5s,playnote,5,E4,endcmd'
               dc    i1'2,playnote,2,E5,playnote,5,C4s,endcmd'
               dc    i1'2,playnote,2,C5s,playnote,5,E4,endcmd'
               dc    i1'2,playnote,2,E5,playnote,5,C4s,endcmd'
               dc    i1'2,playnote,2,C5s,playnote,5,E4,endcmd'
               dc    i1'2,playnote,2,E5,playnote,5,C4s,endcmd'
               dc    i1'32,playnote,1,A5,playnote,2,E5,playnote,3,C5s'
               dc    i1'playnote,4,A4,playnote,5,E4,playnote,6,C4s'
               dc    i1'playnote,7,A3,playnote,8,G3,endcmd'
               dc    i1'32,playnote,1,A5,playnote,2,F5,playnote,3,D5'
               dc    i1'playnote,4,A4,playnote,5,F4,playnote,6,D4'
               dc    i1'playnote,7,A3,playnote,8,F4,endcmd'
;
; measure 28
;
               dc    i1'32,playnote,1,G5,playnote,2,D5,playnote,3,A4s'
               dc    i1'playnote,4,G4,playnote,5,D4,playnote,6,A3s'
               dc    i1'stopnote,7,stopnote,8,endcmd'
               dc    i1'16,stopnote,1,stopnote,2,stopnote,3,stopnote,4'
               dc    i1'stopnote,5,endcmd'
               dc    i1'8,playnote,6,A3,endcmd'
               dc    i1'8,playnote,6,G3,endcmd'
               dc    i1'12,playnote,1,G5,playnote,2,E5,playnote,3,C5s'
               dc    i1'playnote,4,A4,playnote,5,E4,playnote,6,C4s'
               dc    i1'playnote,8,A3,endcmd'
               dc    i1'4,playnote,8,E3,endcmd'
               dc    i1'4,stopnote,1,stopnote,2,stopnote,3,stopnote,4'
               dc    i1'stopnote,5,stopnote,6,playnote,8,F3,endcmd'
               dc    i1'4,playnote,8,D3,endcmd'
               dc    i1'4,playnote,8,E3,endcmd'
               dc    i1'4,playnote,8,C3s,endcmd'
;
; measure 29
;
               dc    i1'4,playnote,8,D3,endcmd'
               dc    i1'4,playnote,8,B2,endcmd'
               dc    i1'4,playnote,8,C3s,endcmd'
               dc    i1'4,playnote,8,A2,endcmd'
               dc    i1'4,playnote,8,A2s,endcmd'
               dc    i1'4,playnote,8,G2s,endcmd'
               dc    i1'4,playnote,8,A2,endcmd'
               dc    i1'8,playnote,1,C5s,playnote,2,A4,playnote,3,E4'
               dc    i1'playnote,4,A3,playnote,8,G3,endcmd'
               dc    i1'16,playnote,1,D5,playnote,2,A4,playnote,3,F4'
               dc    i1'playnote,4,D4,playnote,5,A3,playnote,8,F3,endcmd'
               dc    i1'16,playnote,1,F4,playnote,2,D4,playnote,3,A3'
               dc    i1'playnote,8,D3,stopnote,4,stopnote,5,endcmd'
               dc    i1'16,playnote,1,E4,playnote,8,A2,endcmd'
               dc    i1'8,playnote,2,C4s,endcmd'
               dc    i1'8,playnote,3,G3,endcmd'
;
; measure 30
;
               dc    i1'20,playnote,1,D4,playnote,2,A3,playnote,4,D3'
               dc    i1'playnote,8,D2,playnote,9,D2,endcmd'
               dc    i1'10,playnote,3,F3,endcmd'
               dc    i1'16,playnote,3,E3,endcmd'
               dc    i1'48,playnote,3,F3,endcmd'
               dc    i1'48,stopnote,1,stopnote,2,stopnote,3,stopnote,4'
               dc    i1'stopnote,8,stopnote,9,endcmd'

               dc    i1'0'

               END
