***************************************************************************
*                                                                         *
* Polygonia I                                                             *
* Constants                                                               *
*                                                                         *
***************************************************************************

DrawBufSize    GEQU  2400*5             ;Size of drawing buffer
NumScanLines   GEQU  200                ;Number of scanlines
MaxEdges       GEQU  1000               ;Maximum # of edges
MaxPolygons    GEQU  250                ;Maximum # of polygons
