matrix	gequ	$81
trbptr	gequ	$B1
Index1         gequ  $B5
Index2         gequ  $B6
Index3         gequ  $B7
Index4         gequ  $B8
Index5         gequ  $B9
Color          gequ  $BA
Divisor        gequ  $BC
cox            gequ  $BE
coy            gequ  $C0
Arg1           gequ  $C2
Arg2           gequ  $C6
ScaleX         gequ  $CA
ScaleY         gequ  $CE
ScaleZ         gequ  $D2
PerspD         gequ  $D6
Quotient       gequ  $D8
Result         gequ  $DA
EdgePtr        gequ  $E0
tptr           gequ  $E2
Dx             gequ  $E4
Dy             gequ  $E6
Err            gequ  $E8
EndX           gequ  $EA
EndY           gequ  $EC
StartX         gequ  $EE
StartY         gequ  $F0
sin            gequ  $F2
cos            gequ  $F6
PntPtr         gequ  $FA
;MatPtr         gequ  $FC
ObjPtr         gequ  $FE
